import 'package:food_recipe_app/shared/domain/models/categories/meal_by_categories/meals.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'meal_by_category_list.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'meal_by_category_list.g.dart';

@freezed
class MealByCategoryList with _$MealByCategoryList {
  const factory MealByCategoryList({
    required List<Meals> meals,
  }) = _MealByCategoryList;

  factory MealByCategoryList.fromJson(Map<String, Object?> json)
      => _$MealByCategoryListFromJson(json);
}
