import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'meals.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'meals.g.dart';

@freezed
class Meals with _$Meals {
  const factory Meals({
    String? strMeal,
    String? strMealThumb,
    String? idMeal,
  }) = _Meals;

  factory Meals.fromJson(Map<String, Object?> json)
      => _$MealsFromJson(json);
}

