import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'categories.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'categories.g.dart';

@freezed
class Categories with _$Categories {
  const factory Categories({
    String? idCategory,
    String? strCategory,
    String? strCategoryThumb,
    String? strCategoryDescription,
  }) = _Categories;

  factory Categories.fromJson(Map<String, Object?> json)
      => _$CategoriesFromJson(json);
}

