import 'package:food_recipe_app/shared/domain/models/categories/category_list/categories.dart';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'category_list.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'category_list.g.dart';

@freezed
class CategoryList with _$CategoryList {
  const factory CategoryList({
    required List<Categories> categories,
  }) = _CategoryList;

  factory CategoryList.fromJson(Map<String, Object?> json)
      => _$CategoryListFromJson(json);
}
