
import 'package:food_recipe_app/core/domain/models/meals/meals.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'meal_list.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'meal_list.g.dart';

@freezed
class MealList with _$MealList {
  const factory MealList({
    required List<Meals> meals,
  }) = _MealList;

  factory MealList.fromJson(Map<String, Object?> json)
      => _$MealListFromJson(json);
}