// This file is "person.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'statistic.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'statistic.g.dart';

@freezed
class Statistic with _$Statistic {
  const factory Statistic({
    @Default(0) int recipe,
    @Default(0) int videos,
    @Default(0) int followers,
    @Default(0) int following,
  }) = _Statistic;

  factory Statistic.fromJson(Map<String, Object?> json)
      => _$StatisticFromJson(json);
}
