
import 'package:food_recipe_app/shared/domain/models/notifications/notifications.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notification_list.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notification_list.g.dart';

@freezed
class NotificationList with _$NotificationList {
  const factory NotificationList({
    required List<Notifications> notifications,
  }) = _NotificationList;

  factory NotificationList.fromJson(Map<String, Object?> json)
      => _$NotificationListFromJson(json);
}