import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notifications.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'notifications.g.dart';

@freezed
class Notifications with _$Notifications {
  const factory Notifications({
    String? idNotification,
    String? title,
    String? body,
    String? time,
    @Default(false) bool isToday,
  }) = _Notifications;

  factory Notifications.fromJson(Map<String, Object?> json)
      => _$NotificationsFromJson(json);
}

enum TypeNotification {
  all, unread, read
}
