import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ingredients.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'ingredients.g.dart';

@freezed
class Ingredients with _$Ingredients {
  const factory Ingredients({
    String? idIngredient,
    String? imgIngredient,
    String? nameIngredient,
    String? quantity,
  }) = _Ingredients;

  factory Ingredients.fromJson(Map<String, Object?> json)
      => _$IngredientsFromJson(json);
}
