// This file is "person.dart"
import 'package:food_recipe_app/shared/domain/models/users/statistic.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:food_recipe_app/shared/domain/models/meals/meals.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    String? idUser,
    String? fullName,
    String? intro,
    Statistic? statistic,
    @Default([]) List<Meals> meals,
    @Default('')String avatar
  }) = _User;

  factory User.fromJson(Map<String, Object?> json)
      => _$UserFromJson(json);
}
